<Project>
  <ItemGroup>
    <!-- Aspire Core -->
    <PackageVersion Include="Aspire.Hosting" Version="9.2.0" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.2.0" />
    <PackageVersion Include="Aspire.ServiceDefaults" Version="9.2.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Npgsql" Version="9.0.0" />

    <!-- Aspire Integrations -->
    <PackageVersion Include="Aspire.Hosting.Postgres" Version="9.2.0" />
    <PackageVersion Include="Aspire.EntityFrameworkCore.PostgreSql" Version="9.2.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Process" Version="1.8.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="11.8.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.8.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.8.1" />


    
    <!-- EF Core for PostgreSQL -->
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.3" />

    <!-- MediatR -->
    <PackageVersion Include="MediatR" Version="12.4.0" />
    <PackageVersion Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="12.4.0" />

    <!-- FastEndpoints -->
    <PackageVersion Include="FastEndpoints" Version="5.0.1" />

    <!-- FluentValidation -->
    <PackageVersion Include="FluentValidation" Version="11.7.1" />
  </ItemGroup>
</Project>
